#!/usr/bin/python
# -*- coding: utf-8 -*-

# 这个工具用于将早期版本的歌词文件重新组成新版的目录结构。

# 早期的歌词存在歌词目录下，命名方式为<艺术家 - 标题.lrc>
# 如果歌曲太多，比如作者的歌曲库有3000左右，会在此目录下存放
# 大量文件，不便查看。在新版本中，歌词按照<艺术家/标题.lrc>的
# 目录结构存放，从而产生了歌词文件迁移的问题。

# 使用方法
# 使用如下命令运行：python transfer

import os, gconf

gconf_key = '/apps/rhythmbox/plugins/SogouLyrics/folder'

def transfer():
	conf = gconf.client_get_default()
	rootdir = conf.get_string(gconf_key)
	print 'begin transfer in <%s>' % rootdir
	list = os.listdir(rootdir)
	for lrc in list:
		src = os.path.join(rootdir, lrc)
		if (os.path.isfile(src) and lrc.endswith('.lrc')):
			print 'transferring <%s>' % (lrc)
			try:
				pos = lrc.find(' - ')
				if (pos != -1):
					subdir = os.path.join(rootdir, lrc[:pos])
					filename = lrc[pos+3:]
					if (not os.path.exists(subdir)):
						os.makedirs(subdir)
					dst = os.path.join(subdir, filename)
					os.rename(src, dst)
			except Exception as e:
				print e
	print 'transer finished'
	return

if __name__ == '__main__':
	transfer()
